# Build (custom-built image with node and yarn - https://github.com/yarnpkg/yarn/blob/master/Dockerfile.dev)
FROM yarn as build

COPY . .
RUN yarn install && yarn webpack

# Run
FROM nginx:latest

EXPOSE 80

COPY --from=build public/bundle/ /usr/share/nginx/html
RUN rm /usr/share/nginx/html/index.html
COPY --from=build nginx.conf /etc/nginx/conf.d/default.conf
